name: CI Backend Java

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend-java-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push backend-java Docker image (dev)
      run: |
        TAG=${{ github.sha }}
        docker build -f backend-java/Dockerfile -t ${{ secrets.AZURE_URL }}/backend-java:$TAG ./backend-java
        docker push ${{ secrets.AZURE_URL }}/backend-java:$TAG

    - name: Deploy backend-java to Kubernetes (dev)
      run: |
        TAG=${{ github.sha }}
        sed -i 's|eduazureregistry.azurecr.io/backend-java:.*|${{ secrets.AZURE_URL }}/backend-java:$TAG|g' manifests/backend-java/base/deployment.yaml
        kubectl apply -k manifests/backend-java/overlays/dev
