name: CI Backend Java

on:
  workflow_dispatch:

jobs:
  build-and-push-backend-java-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.AZURE_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./dockerfile/backend-java/Dockerfile
        file: Dockerfile
        push: true
        tags: ${{ secrets.AZURE_URL }}/backend-java:${{ github.event.inputs.name }}-${{ env.DATE_TAG }}

    - name: Update Kustomize Deployment with New Tag
      run: |
        TAG="${{ secrets.AZURE_URL }}/backend-java:${{ github.event.inputs.name }}-${{ env.DATE_TAG }}"
        sed -i "s|\(image: backend-java\).*|\1:$TAG|" ./manifest/backend-java/base/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./manifests/backend-vue/overlays/dev/kustomization.yaml
        git commit -m "Update backend-java-deployment.yaml with tag $TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

